trigger:
  - main

pr:
  - main

stages:
  - stage: SecurityScanners
    variables:
      - group: boost-prod
      - name: api_token
        value: $[variables.BOOST_API_TOKEN]
    jobs:
      - job:
        steps:
          - task: BoostSecurityScan@1
            inputs:
              apiToken: $(api_token)
              registryModule: boostsecurityio/native-scanner
