trigger:
  - main

pr:
  - main

resources:
  repositories:
    - repository: boostsecurity
      type: github
      name: boostsecurityio/boostsec-scanner-azure
      ref: refs/tags/v4

variables:
  - group: boost-prod
  - name: api_token
    value: $[variables.BOOST_API_TOKEN]

steps:
  - checkout: self
    clean: true
    fetchDepth: 1
    persistCredentials: true

  - template: scanner.yaml@boostsecurity
    parameters:
      api_enabled: false
      registry_module: boostsecurityio/native-scanner

  - template: templates/scanner.yaml
    parameters:
      api_token: $(api_token)
      registry_module: boostsecurityio/native-scanner
