trigger:
  - main

pr:
  - main

variables:
  - name: PublisherId
    value: "BoostSecurity"
  - name: ServiceName
    value: "boostsec-azure-pipeline-publisher"
  - name: isMain
    value: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]

stages:
  - stage: Dev_Test
    condition: eq(variables.isMain, 'false')
    jobs:
      - job:
        steps:
          - template: stages/test.yaml
  - stage: Dev_Package
    dependsOn: Dev_Test
    variables:
      - name: ExtensionId
        value: "BoostSecurityScanDev"
      - name: ExtensionName
        value: "BoostSecurity Scanner Dev"
      - name: ManifestFile
        value: "vss-extension.dev.json"
    jobs:
      - job:
        steps:
          - template: stages/package.yaml
  - stage: Dev_Publish
    dependsOn: Dev_Package
    variables:
      - name: ExtensionId
        value: "BoostSecurityScanDev"
      - name: ExtensionName
        value: "BoostSecurity Scanner Dev"
    jobs:
      - job:
        steps:
          - template: stages/publish.yaml
